<?php

declare(strict_types=1);

namespace EBethus\LaravelTicketBAI\Tests\Unit;

use EBethus\LaravelTicketBAI\Tests\TestCase;
use EBethus\LaravelTicketBAI\TicketBAI;
use Illuminate\Support\Str;

/**
 * Integration test to validate invoice number generation
 * Validates that ULID is truncated to exactly 20 characters for TicketBAI compliance
 */
class InvoiceNumberIntegrationTest extends TestCase
{
    /** @test */
    public function ulid_generation_produces_26_chars_before_truncation()
    {
        // Raw ULID always produces 26 characters
        $rawUlid = (string) Str::ulid();
        
        $this->assertSame(26, strlen($rawUlid), 
            "Raw ULID should be 26 chars. TicketBAI requires max 20 chars.");
        
        echo "\n✓ Raw ULID (26 chars): $rawUlid\n";
    }

    /** @test */
    public function ticketbai_invoice_number_is_truncated_to_20_chars()
    {
        // This is what the TicketBAI::getInvoiceNumber() does internally
        $truncated = substr((string) Str::ulid(), 0, 20);
        
        $this->assertSame(20, strlen($truncated),
            "Truncated ULID must be exactly 20 characters for TicketBAI XSD compliance");
        
        echo "\n✓ Truncated ULID (20 chars): $truncated\n";
    }

    /** @test */
    public function invoice_generation_uses_20_char_truncated_number()
    {
        $ticketbai = new TicketBAI([]);
        
        // Access via reflection
        $reflection = new \ReflectionClass($ticketbai);
        $method = $reflection->getMethod('getInvoiceNumber');
        $method->setAccessible(true);
        
        $invoiceNumber = $method->invoke($ticketbai);
        
        $this->assertSame(20, strlen($invoiceNumber),
            "Invoice number generated by TicketBAI must be 20 characters");
        $this->assertMatchesRegularExpression(
            '/^[0-9A-Z]{20}$/',
            $invoiceNumber,
            "Invoice number must be valid ULID prefix (20 alphanumeric chars)"
        );
        
        echo "\n✓ TicketBAI invoice number (20 chars): $invoiceNumber\n";
        echo "\n✅ XSD Compliance: TicketBAI numero de factura has max 20 chars (was requiring 26 before)\n";
    }
}
